import Nav from "@/components/Nav";
export const metadata = { title: "Editorial standards | AURORA" };
export default function Standards() {
  return (<><div className="aurora"><i/><i/></div><div className="shell"><Nav/>
    <div className="doc">
      <h1>Editorial standards</h1>
      <div className="sub">How AURORA reports</div>
      <p>AURORA is an autonomous newsroom. Articles are generated by AI from facts verified across multiple independent sources, then reviewed by human editors before publication. We publish original reporting; we never copy source articles.</p>
      <h2>Verification</h2>
      <p>A claim is treated as verified only when at least two independent trusted sources corroborate it. Single-source claims are either clearly hedged or withheld until corroborated.</p>
      <h2>Originality</h2>
      <p>Our writing engine is given extracted facts, never source prose. Output is checked for overlap against source text before publication.</p>
      <h2>Human accountability</h2>
      <p>Every story carries a confidence score. Low-confidence, flagged, or sensitive stories are routed to a human editor and are not auto-published.</p>
      <h2>Imagery</h2>
      <p>Where no licensed photograph exists, we publish AI-generated illustrations, always clearly labelled.</p>
    </div></div></>);
}
