import { notFound } from "next/navigation";
import Link from "next/link";
import type { Metadata } from "next";
import Nav from "@/components/Nav";
import ReadingProgress from "@/components/ReadingProgress";
import { getAll, getBySlug, getPublished, fmtDate, SITE } from "@/lib/articles";

type Params = { category: string; slug: string };

export function generateStaticParams() {
  return getAll().map((a) => ({ category: a.category.toLowerCase(), slug: a.slug }));
}

export function generateMetadata({ params }: { params: Params }): Metadata {
  const a = getBySlug(params.category, params.slug);
  if (!a) return { title: "Not found · AURORA" };
  return {
    title: `${a.headline} | AURORA`,
    description: a.summary,
    alternates: { canonical: `${SITE}/${a.category.toLowerCase()}/${a.slug}` },
    openGraph: { title: a.headline, description: a.summary, type: "article" },
  };
}

export default function ArticlePage({ params }: { params: Params }) {
  const a = getBySlug(params.category, params.slug);
  if (!a) notFound();

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "NewsArticle",
    headline: a.headline,
    description: a.summary,
    articleSection: a.category,
    datePublished: a.publishedAt,
    dateModified: a.publishedAt,
    author: { "@type": "Organization", name: "AURORA Newsroom AI" },
    publisher: { "@type": "Organization", name: "AURORA" },
    mainEntityOfPage: { "@type": "WebPage", "@id": `${SITE}/${a.category.toLowerCase()}/${a.slug}` },
    isAccessibleForFree: true,
  };

  const related = getPublished().filter((x) => x.id !== a.id).slice(0, 3);

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <ReadingProgress />
      <div className="aurora"><i /><i /></div>
      <div className="shell">
        <Nav />
        <main className="amain">
          <div className="crumbs">
            {a.breaking && <span className="brk">● BREAKING</span>}
            <span className="cat">{a.category}</span>
            <span>·</span>
            <span>{fmtDate(a.publishedAt)}</span>
          </div>
          <h1>{a.headline}</h1>
          <p className="deck">{a.summary}</p>

          <div className="byline">
            <div className="av">AI</div>
            <div className="who"><b>AURORA Newsroom AI</b><span>Reviewed by Editorial Desk</span></div>
            <span className="sep" />
            <span>{a.readingTimeMin} min read</span>
            <span className="conf"><span className="d" />Confidence {a.scores.confidence.toFixed(2)}</span>
          </div>

          <div className="feat"><div className="img" /><span className="label">{a.featuredImageLabel}</span></div>
          <p className="cap">Illustration generated by AURORA and labelled as AI-generated. No licensed photograph was available at publication.</p>

          <article>
            {a.body.map((p, i) => (
              <p key={i} className={i === 0 ? "first" : ""}>{p}</p>
            ))}
            {a.pullQuote && <div className="pull">&ldquo;{a.pullQuote}&rdquo;</div>}

            <div className="bh">Key facts</div>
            <div className="abox"><ul className="kf">{a.keyFacts.map((k, i) => <li key={i}>{k}</li>)}</ul></div>

            <div className="bh">Timeline of events</div>
            <div className="abox"><ul className="tl">{a.timeline.map(([when, what], i) => (
              <li key={i}><div className="when">{when}</div><div className="what">{what}</div></li>
            ))}</ul></div>

            <div className="bh">Background</div>
            <p style={{ fontFamily: "var(--serif)", fontSize: 18, lineHeight: 1.85, color: "var(--read)" }}>{a.background}</p>

            <div className="bh">Possible future impact</div>
            <p style={{ fontFamily: "var(--serif)", fontSize: 18, lineHeight: 1.85, color: "var(--read)" }}>{a.futureImpact}</p>

            <div className="bh">How this story was produced</div>
            <div className="abox">
              <div className="tgrid">
                <div>
                  <Sb label="Originality" v={a.scores.originality} />
                  <Sb label="Source reliability" v={a.scores.sourceReliability} />
                  <Sb label="Fact-check grounding" v={a.scores.factCheck} />
                  <Sb label="Confidence" v={a.scores.confidence} />
                </div>
                <div className="disc">
                  <div className="hd">AI disclosure</div>
                  This article was written by AURORA&rsquo;s newsroom AI from facts verified across multiple
                  independent sources, then reviewed by a human editor before publication. No source article was
                  copied, and every claim was corroborated by at least two sources.
                </div>
              </div>
            </div>

            <div className="bh">Sources</div>
            <div className="abox">
              <div className="src">
                {a.sources.map((s, i) => (
                  <div className="s" key={i}>
                    <div className="nm">{s.name}<div className="u">{s.url}</div></div>
                    <div className="rel"><span>{s.reliability.toFixed(2)}</span><div className="t"><i style={{ width: `${s.reliability * 100}%` }} /></div></div>
                  </div>
                ))}
              </div>
            </div>

            <div className="bh">Related topics</div>
            <div className="chips">{a.relatedTopics.map((t, i) => <span className="chip" key={i}>{t}</span>)}</div>

            <div className="bh">More from the wire</div>
            <div className="grid">
              {related.map((r) => (
                <Link key={r.id} href={`/${r.category.toLowerCase()}/${r.slug}`} className="card">
                  <div className="top"><span className="ai">{r.featuredImageLabel}</span></div>
                  <div className="b">
                    <span className="tag cat">{r.category}</span>
                    <h3>{r.headline}</h3>
                  </div>
                </Link>
              ))}
            </div>

            <div className="correct">
              Spotted an error? <Link href="/corrections">Report a correction</Link> · Corrections are logged publicly and the article is versioned.<br />
              © 2026 AURORA · AI-assisted, human-accountable journalism
            </div>
          </article>
        </main>
      </div>
    </>
  );
}

function Sb({ label, v }: { label: string; v: number }) {
  return (
    <div className="sb">
      <div className="r"><span>{label}</span><b>{Math.round(v * 100)}%</b></div>
      <div className="t"><i style={{ width: `${Math.round(v * 100)}%` }} /></div>
    </div>
  );
}
